destination: _site
sass:
  sass_dir: _sass
  style: compressed

# permalink and highlighter
permalink   : /:year/:month/:day/:title/
markdown    : kramdown
highlighter : rouge

# SEO settings
title: KtorZ's Blog
description: "Computer Science and Philosophy"
keywords: "KtorZ, github, developer, blog, software engineer, matthias, benkort"

# Site settings
url: http://ktorz.github.io
baseurl: ""

# Author settings
author:
  name      : Matthias Benkort
  job       : Software Engineer
  bio       : "Functional programming enthusiast; frontend and backend Software engineer with a strong interest in machine learning"
  thumb     : /img/ktorz.png
  email     : matthias.benkort@gmail.com
  url       : http://ktorz.github.io
  github    : http://github.com/KtorZ
  twitter   : http://twitter.com/mbenkort
  linkedin  : http://linkedin.com/in/matthias-benkort-47186a57
  stack_exchange: http://stackoverflow.com/users/2542201/ktorz

google_analytics: UA-70152327-1
repo: http://github.com/KtorZ/ktorz.github.io

# comments
disqus_shortname: "ktorz"
